version: "3"

tasks:
    build:
        desc: Build the app
        cmds:
            - GOFLAGS=-mod=mod go build -o bin/gopher-cli.exe main.go 

    run: 
        desc: Run the app
        cmds:
            - GOFLAGS=-mod=mod go run main.go

    clean:
        desc: Remove all retrieved *.png files
        dir: bin #Must mention the directory to be cleaned from
        cmds:
            - powershell -Command "Write-Host 'Current Directory:'; pwd"
            - powershell -Command "Write-Host 'Listing PNG files before deletion:'; Get-ChildItem -Path *.png"
            - powershell -Command "Write-Host 'Attempting to delete PNG files...'; Remove-Item -Path *.png -Force"
            - powershell -Command "Write-Host 'Listing PNG files after deletion:'; Get-ChildItem -Path *.png"
